// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protos/activities_v1.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActivitiesClient is the client API for Activities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivitiesClient interface {
	GetPartyActivities(ctx context.Context, in *PartyActivityPageRequest, opts ...grpc.CallOption) (*PartyActivityPageReply, error)
	LogPartyActivity(ctx context.Context, in *PartyActivityLogRequest, opts ...grpc.CallOption) (*PartyActivityObjectReply, error)
	BatchPartyActivities(ctx context.Context, in *PartyActivityBatchRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error)
	DeletePartyActivities(ctx context.Context, in *PartyActivityDeleteRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error)
}

type activitiesClient struct {
	cc grpc.ClientConnInterface
}

func NewActivitiesClient(cc grpc.ClientConnInterface) ActivitiesClient {
	return &activitiesClient{cc}
}

func (c *activitiesClient) GetPartyActivities(ctx context.Context, in *PartyActivityPageRequest, opts ...grpc.CallOption) (*PartyActivityPageReply, error) {
	out := new(PartyActivityPageReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/get_party_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) LogPartyActivity(ctx context.Context, in *PartyActivityLogRequest, opts ...grpc.CallOption) (*PartyActivityObjectReply, error) {
	out := new(PartyActivityObjectReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/log_party_activity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) BatchPartyActivities(ctx context.Context, in *PartyActivityBatchRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error) {
	out := new(PartyActivityOnlyErrorReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/batch_party_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) DeletePartyActivities(ctx context.Context, in *PartyActivityDeleteRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error) {
	out := new(PartyActivityOnlyErrorReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/delete_party_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivitiesServer is the server API for Activities service.
// All implementations must embed UnimplementedActivitiesServer
// for forward compatibility
type ActivitiesServer interface {
	GetPartyActivities(context.Context, *PartyActivityPageRequest) (*PartyActivityPageReply, error)
	LogPartyActivity(context.Context, *PartyActivityLogRequest) (*PartyActivityObjectReply, error)
	BatchPartyActivities(context.Context, *PartyActivityBatchRequest) (*PartyActivityOnlyErrorReply, error)
	DeletePartyActivities(context.Context, *PartyActivityDeleteRequest) (*PartyActivityOnlyErrorReply, error)
	mustEmbedUnimplementedActivitiesServer()
}

// UnimplementedActivitiesServer must be embedded to have forward compatible implementations.
type UnimplementedActivitiesServer struct {
}

func (UnimplementedActivitiesServer) GetPartyActivities(context.Context, *PartyActivityPageRequest) (*PartyActivityPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartyActivities not implemented")
}
func (UnimplementedActivitiesServer) LogPartyActivity(context.Context, *PartyActivityLogRequest) (*PartyActivityObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogPartyActivity not implemented")
}
func (UnimplementedActivitiesServer) BatchPartyActivities(context.Context, *PartyActivityBatchRequest) (*PartyActivityOnlyErrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPartyActivities not implemented")
}
func (UnimplementedActivitiesServer) DeletePartyActivities(context.Context, *PartyActivityDeleteRequest) (*PartyActivityOnlyErrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePartyActivities not implemented")
}
func (UnimplementedActivitiesServer) mustEmbedUnimplementedActivitiesServer() {}

// UnsafeActivitiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivitiesServer will
// result in compilation errors.
type UnsafeActivitiesServer interface {
	mustEmbedUnimplementedActivitiesServer()
}

func RegisterActivitiesServer(s grpc.ServiceRegistrar, srv ActivitiesServer) {
	s.RegisterService(&Activities_ServiceDesc, srv)
}

func _Activities_GetPartyActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).GetPartyActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/get_party_activities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).GetPartyActivities(ctx, req.(*PartyActivityPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_LogPartyActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).LogPartyActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/log_party_activity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).LogPartyActivity(ctx, req.(*PartyActivityLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_BatchPartyActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).BatchPartyActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/batch_party_activities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).BatchPartyActivities(ctx, req.(*PartyActivityBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_DeletePartyActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).DeletePartyActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/delete_party_activities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).DeletePartyActivities(ctx, req.(*PartyActivityDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Activities_ServiceDesc is the grpc.ServiceDesc for Activities service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Activities_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activities_v1.Activities",
	HandlerType: (*ActivitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_party_activities",
			Handler:    _Activities_GetPartyActivities_Handler,
		},
		{
			MethodName: "log_party_activity",
			Handler:    _Activities_LogPartyActivity_Handler,
		},
		{
			MethodName: "batch_party_activities",
			Handler:    _Activities_BatchPartyActivities_Handler,
		},
		{
			MethodName: "delete_party_activities",
			Handler:    _Activities_DeletePartyActivities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/activities_v1.proto",
}
